USE [master]
GO

/****** Object:  Database [BD_Baratico]    Script Date: 2/12/2018 3:06:25 PM ******/
CREATE DATABASE [BD_Baratico]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_Baratico', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\BD_Baratico.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BD_Baratico_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\BD_Baratico_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BD_Baratico] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_Baratico].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD_Baratico] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BD_Baratico] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BD_Baratico] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BD_Baratico] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BD_Baratico] SET ARITHABORT OFF 
GO

ALTER DATABASE [BD_Baratico] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BD_Baratico] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BD_Baratico] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BD_Baratico] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BD_Baratico] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BD_Baratico] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BD_Baratico] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BD_Baratico] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BD_Baratico] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BD_Baratico] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BD_Baratico] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BD_Baratico] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BD_Baratico] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BD_Baratico] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BD_Baratico] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BD_Baratico] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BD_Baratico] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BD_Baratico] SET RECOVERY FULL 
GO

ALTER DATABASE [BD_Baratico] SET  MULTI_USER 
GO

ALTER DATABASE [BD_Baratico] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BD_Baratico] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BD_Baratico] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BD_Baratico] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BD_Baratico] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BD_Baratico] SET  READ_WRITE 
GO

USE [BD_Baratico]
GO

/****** Object:  Table [dbo].[ADMINISTRADOR]    Script Date: 2/12/2018 3:06:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ADMINISTRADOR](
	[IdAdiministrador] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nchar](20) NOT NULL,
	[Apellidos] [nchar](40) NOT NULL,
 CONSTRAINT [PK_ADMINISTRADORES] PRIMARY KEY CLUSTERED 
(
	[IdAdiministrador] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [BD_Baratico]
GO

/****** Object:  Table [dbo].[CALIFICACION_CLIXPRO]    Script Date: 2/12/2018 3:07:00 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CALIFICACION_CLIXPRO](
	[IdCalificacion] [int] IDENTITY(1,1) NOT NULL,
	[IdCliente] [int] NOT NULL,
	[IdProducto] [int] NOT NULL,
	[Calificacion] [int] NOT NULL,
 CONSTRAINT [PK_CALIFICACION_CLIXPRO] PRIMARY KEY CLUSTERED 
(
	[IdCalificacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [BD_Baratico]
GO

/****** Object:  Table [dbo].[CARRITO]    Script Date: 2/12/2018 3:07:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CARRITO](
	[IdCarrito] [int] IDENTITY(1,1) NOT NULL,
	[Total] [int] NOT NULL,
	[IdCliente] [int] NOT NULL,
	[Pagado] [char](1) NOT NULL,
	[Fecha] [datetime] NULL,
 CONSTRAINT [PK_CARRITO] PRIMARY KEY CLUSTERED 
(
	[IdCarrito] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [BD_Baratico]
GO

/****** Object:  Table [dbo].[CATEGORIA]    Script Date: 2/12/2018 3:07:51 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CATEGORIA](
	[IdCategoría] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nchar](20) NOT NULL,
 CONSTRAINT [PK_CATEGORIAS] PRIMARY KEY CLUSTERED 
(
	[IdCategoría] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [BD_Baratico]
GO

/****** Object:  Table [dbo].[CLIENTE]    Script Date: 2/12/2018 3:08:01 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENTE](
	[IdCliente] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nchar](20) NOT NULL,
	[Apellidos] [nchar](40) NOT NULL,
	[CorreoElectronico] [nchar](50) NOT NULL,
	[Direccion] [nchar](200) NULL,
 CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[IdCliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [BD_Baratico]
GO

/****** Object:  Table [dbo].[COMENTARIOXPRODUCTO]    Script Date: 2/12/2018 3:08:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMENTARIOXPRODUCTO](
	[IdComentario] [int] IDENTITY(1,1) NOT NULL,
	[IdProducto] [int] NOT NULL,
	[IdCliente] [int] NOT NULL,
	[Comentario] [nchar](200) NOT NULL,
 CONSTRAINT [PK_COMENTARIOXPRODUCTO] PRIMARY KEY CLUSTERED 
(
	[IdComentario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [BD_Baratico]
GO

/****** Object:  Table [dbo].[LOG_IN]    Script Date: 2/12/2018 3:09:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LOG_IN](
	[IdLogIn] [int] IDENTITY(1,1) NOT NULL,
	[Usuario] [nchar](15) NOT NULL,
	[Clave] [nchar](20) NOT NULL,
	[Tipo] [int] NOT NULL,
	[IdDueño] [int] NOT NULL,
 CONSTRAINT [PK_LOG_IN] PRIMARY KEY CLUSTERED 
(
	[IdLogIn] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [BD_Baratico]
GO

/****** Object:  Table [dbo].[MENSAJE]    Script Date: 2/12/2018 3:09:28 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MENSAJE](
	[IdMensaje] [int] IDENTITY(1,1) NOT NULL,
	[idCliente] [int] NOT NULL,
	[idAdministrador] [int] NULL,
	[ClienteMensajero] [char](1) NOT NULL,
	[Mensaje] [text] NOT NULL,
 CONSTRAINT [PK_MENSAJE] PRIMARY KEY CLUSTERED 
(
	[IdMensaje] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [BD_Baratico]
GO

/****** Object:  Table [dbo].[OFERTA]    Script Date: 2/12/2018 3:09:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[OFERTA](
	[IdOferta] [int] IDENTITY(1,1) NOT NULL,
	[IdProducto] [int] NOT NULL,
	[FechaInicio] [datetime] NOT NULL,
	[FechaFin] [datetime] NULL,
 CONSTRAINT [PK_OFERTA] PRIMARY KEY CLUSTERED 
(
	[IdOferta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [BD_Baratico]
GO

/****** Object:  Table [dbo].[PRODUCTO]    Script Date: 2/12/2018 3:10:01 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUCTO](
	[IdProducto] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nchar](20) NOT NULL,
	[idCategoría] [int] NOT NULL,
	[CantidadVendida] [int] NOT NULL,
	[Precio] [int] NOT NULL,
	[CalificacionPromedio] [int] NOT NULL,
 CONSTRAINT [PK_PRODUCTOS] PRIMARY KEY CLUSTERED 
(
	[IdProducto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [BD_Baratico]
GO

/****** Object:  Table [dbo].[PRODUCTOXCARRITO]    Script Date: 2/12/2018 3:10:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUCTOXCARRITO](
	[IdPxC] [int] IDENTITY(1,1) NOT NULL,
	[IdProducto] [int] NOT NULL,
	[IdCarrito] [int] NOT NULL,
	[Cantidad] [int] NOT NULL,
	[PrecioUnitario] [int] NOT NULL,
	[SubTotal] [int] NULL,
 CONSTRAINT [PK_PRODUCTOXCARRITO] PRIMARY KEY CLUSTERED 
(
	[IdPxC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[PRODUCTOXCARRITO]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTOXCARRITO_CARRITO] FOREIGN KEY([IdCarrito])
REFERENCES [dbo].[CARRITO] ([IdCarrito])
GO

ALTER TABLE [dbo].[PRODUCTOXCARRITO] CHECK CONSTRAINT [FK_PRODUCTOXCARRITO_CARRITO]
GO

ALTER TABLE [dbo].[PRODUCTOXCARRITO]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTOXCARRITO_PRODUCTO] FOREIGN KEY([IdProducto])
REFERENCES [dbo].[PRODUCTO] ([IdProducto])
GO

ALTER TABLE [dbo].[PRODUCTOXCARRITO] CHECK CONSTRAINT [FK_PRODUCTOXCARRITO_PRODUCTO]
GO

ALTER TABLE [dbo].[PRODUCTO]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTOS_CATEGORIAS] FOREIGN KEY([idCategoría])
REFERENCES [dbo].[CATEGORIA] ([IdCategoría])
GO

ALTER TABLE [dbo].[PRODUCTO] CHECK CONSTRAINT [FK_PRODUCTOS_CATEGORIAS]
GO

ALTER TABLE [dbo].[OFERTA]  WITH CHECK ADD  CONSTRAINT [FK_OFERTA_PRODUCTO] FOREIGN KEY([IdProducto])
REFERENCES [dbo].[PRODUCTO] ([IdProducto])
GO

ALTER TABLE [dbo].[OFERTA] CHECK CONSTRAINT [FK_OFERTA_PRODUCTO]
GO

ALTER TABLE [dbo].[MENSAJE]  WITH CHECK ADD  CONSTRAINT [FK_MENSAJE_ADMINISTRADOR] FOREIGN KEY([idAdministrador])
REFERENCES [dbo].[ADMINISTRADOR] ([IdAdiministrador])
GO

ALTER TABLE [dbo].[MENSAJE] CHECK CONSTRAINT [FK_MENSAJE_ADMINISTRADOR]
GO

ALTER TABLE [dbo].[MENSAJE]  WITH CHECK ADD  CONSTRAINT [FK_MENSAJE_CLIENTE] FOREIGN KEY([idCliente])
REFERENCES [dbo].[CLIENTE] ([IdCliente])
GO

ALTER TABLE [dbo].[MENSAJE] CHECK CONSTRAINT [FK_MENSAJE_CLIENTE]
GO

ALTER TABLE [dbo].[COMENTARIOXPRODUCTO]  WITH CHECK ADD  CONSTRAINT [FK_COMENTARIOXPRODUCTO_CLIENTE] FOREIGN KEY([IdCliente])
REFERENCES [dbo].[CLIENTE] ([IdCliente])
GO

ALTER TABLE [dbo].[COMENTARIOXPRODUCTO] CHECK CONSTRAINT [FK_COMENTARIOXPRODUCTO_CLIENTE]
GO

ALTER TABLE [dbo].[COMENTARIOXPRODUCTO]  WITH CHECK ADD  CONSTRAINT [FK_COMENTARIOXPRODUCTO_PRODUCTO] FOREIGN KEY([IdProducto])
REFERENCES [dbo].[PRODUCTO] ([IdProducto])
GO

ALTER TABLE [dbo].[COMENTARIOXPRODUCTO] CHECK CONSTRAINT [FK_COMENTARIOXPRODUCTO_PRODUCTO]
GO


ALTER TABLE [dbo].[CALIFICACION_CLIXPRO]  WITH CHECK ADD  CONSTRAINT [FK_CALIFICACION_CLIXPRO_CLIENTE] FOREIGN KEY([IdCliente])
REFERENCES [dbo].[CLIENTE] ([IdCliente])
GO

ALTER TABLE [dbo].[CALIFICACION_CLIXPRO] CHECK CONSTRAINT [FK_CALIFICACION_CLIXPRO_CLIENTE]
GO

ALTER TABLE [dbo].[CALIFICACION_CLIXPRO]  WITH CHECK ADD  CONSTRAINT [FK_CALIFICACION_CLIXPRO_PRODUCTO] FOREIGN KEY([IdProducto])
REFERENCES [dbo].[PRODUCTO] ([IdProducto])
GO

ALTER TABLE [dbo].[CALIFICACION_CLIXPRO] CHECK CONSTRAINT [FK_CALIFICACION_CLIXPRO_PRODUCTO]
GO

ALTER TABLE [dbo].[CARRITO]  WITH CHECK ADD  CONSTRAINT [FK_CARRITO_CLIENTE] FOREIGN KEY([IdCliente])
REFERENCES [dbo].[CLIENTE] ([IdCliente])
GO

ALTER TABLE [dbo].[CARRITO] CHECK CONSTRAINT [FK_CARRITO_CLIENTE]
GO